create table "public"."forms" (
    "id" bigint generated by default as identity not null,
    "team" text not null,
    "name" text not null default 'Form'::text,
    "sections" jsonb not null
);


alter table "public"."forms" enable row level security;

create table "public"."responses" (
    "id" bigint generated by default as identity,
    "team" text not null,
    "scout" uuid not null,
    "form" bigint not null,
    "name" text not null,
    "data" jsonb not null
);


alter table "public"."responses" enable row level security;

create table "public"."scouts" (
    "admin" boolean not null default false,
    "team" text not null,
    "email" text not null,
    "name" text,
    "accepted" boolean not null default false,
    "id" uuid not null
);


alter table "public"."scouts" enable row level security;

create table "public"."teams" (
    "team_id" text not null,
    "email" text not null,
    "team_name" text not null,
    "verified" boolean not null default false
);


alter table "public"."teams" enable row level security;

CREATE UNIQUE INDEX forms_pkey ON public.forms USING btree (id);

CREATE UNIQUE INDEX responses_pkey ON public.responses USING btree (id);

CREATE UNIQUE INDEX scouts_pkey ON public.scouts USING btree (id);

CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (team_id);

alter table "public"."forms" add constraint "forms_pkey" PRIMARY KEY using index "forms_pkey";

alter table "public"."responses" add constraint "responses_pkey" PRIMARY KEY using index "responses_pkey";

alter table "public"."scouts" add constraint "scouts_pkey" PRIMARY KEY using index "scouts_pkey";

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."forms" add constraint "forms_team_fkey" FOREIGN KEY (team) REFERENCES teams(team_id) not valid;

alter table "public"."forms" validate constraint "forms_team_fkey";

alter table "public"."responses" add constraint "responses_form_fkey" FOREIGN KEY (form) REFERENCES forms(id) not valid;

alter table "public"."responses" validate constraint "responses_form_fkey";

alter table "public"."responses" add constraint "responses_scout_fkey" FOREIGN KEY (scout) REFERENCES scouts(id) not valid;

alter table "public"."responses" validate constraint "responses_scout_fkey";

alter table "public"."responses" add constraint "responses_team_fkey" FOREIGN KEY (team) REFERENCES teams(team_id) not valid;

alter table "public"."responses" validate constraint "responses_team_fkey";

alter table "public"."scouts" add constraint "scouts_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."scouts" validate constraint "scouts_id_fkey";

alter table "public"."scouts" add constraint "scouts_team_fkey" FOREIGN KEY (team) REFERENCES teams(team_id) not valid;

alter table "public"."scouts" validate constraint "scouts_team_fkey";


